apiVersion: apps/v1 
kind: Deployment
metadata:
  name: vprormq
spec:
  selector:
    matchLabels:
      app: vprormq
  replicas: 1
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
      - name: vprormq
        image: rabbitmq
        resources:

        ports:
         - name: vprormq-port
           containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"